'use client';
import { useState } from 'react'; import { useRouter } from 'next/navigation';

export default function Login(){
 const [mode,setMode]=useState<'login'|'register'>('login');
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[error,setError]=useState('');
 const [pending2fa,setPending2fa]=useState(false),[code,setCode]=useState('');const [loading,setLoading]=useState(false); const router=useRouter();
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setLoading(true);const endpoint=mode==='login'?'/api/auth/login':'/api/auth/register';const body=mode==='login'?{email,password}:{name,email,password};try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok){setError(data.error||'Request failed');setLoading(false);return}if(data.requiresTwoFactor){setPending2fa(true);setLoading(false);return}router.push('/dashboard');router.refresh()}catch{setError('Network error');setLoading(false)}};
 const verify=async(e:React.FormEvent)=>{e.preventDefault();setError('');setLoading(true);try{const r=await fetch('/api/auth/2fa/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const data=await r.json();if(!r.ok){setError(data.error||'Verification failed');setLoading(false);return}router.push('/dashboard');router.refresh()}catch{setError('Network error');setLoading(false)}};
 return <div className="auth"><div className="card auth-card"><div className="logo" style={{paddingLeft:0}}>CAREERLY <span>OS</span></div><div className="eyebrow">Autonomous career agent</div>{pending2fa?<><h1 className="h1">Authenticator verification</h1><p className="muted">Enter the six-digit code from your authenticator app.</p><form onSubmit={verify} className="stack"><div><label className="label" htmlFor="auth-code">Authentication code</label><input id="auth-code" className="input" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></div>{error&&<div className="pill red" role="alert">{error}</div>}<button className="btn primary" disabled={loading}>{loading?'Verifying…':'Verify and continue'}</button></form></>:<><h1 className="h1">{mode==='login'?'Sign in':'Create your account'}</h1><p className="muted">Use your own email and password. No demo credentials are prefilled.</p><form onSubmit={submit} className="stack">{mode==='register'&&<div><label className="label" htmlFor="register-name">Name</label><input id="register-name" className="input" required value={name} onChange={e=>setName(e.target.value)}/></div>}<div><label className="label" htmlFor="login-email">Email</label><input id="login-email" className="input" type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></div><div><label className="label" htmlFor="login-password">Password</label><input id="login-password" className="input" type="password" required minLength={12} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} />{mode==='register'&&<div className="kicker" style={{marginTop:5}}>Minimum 12 characters. Use a unique password with uppercase, lowercase, number, and symbol.</div>}</div>{error&&<div className="pill red" role="alert">{error}</div>}<button className="btn primary" disabled={loading}>{loading?(mode==='login'?'Signing in…':'Creating account…'):(mode==='login'?'Sign in':'Create account')}</button></form><button className="btn" style={{width:'100%',marginTop:10}} onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Create a new account':'I already have an account'}</button></>}</div></div>
}
