'use client';
import { useEffect, useState } from 'react';

export default function Security(){
 const [user,setUser]=useState<any>(null),[qr,setQr]=useState(''),[secret,setSecret]=useState(''),[code,setCode]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{fetch('/api/auth/me').then(r=>r.json()).then(d=>setUser(d.user))},[]);
 const setup=async()=>{setMessage('');setLoading(true);const r=await fetch('/api/auth/2fa/setup',{method:'POST'});const d=await r.json();setLoading(false);if(!r.ok){setMessage(d.error);return}setQr(d.qr);setSecret(d.secret);};
 const verify=async()=>{setMessage('');const r=await fetch('/api/auth/2fa/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const d=await r.json();if(!r.ok){setMessage(d.error);return}setMessage('Two-factor authentication is enabled.');setQr('');setSecret('');const me=await fetch('/api/auth/me').then(x=>x.json());setUser(me.user)};
 const disable=async()=>{const r=await fetch('/api/auth/2fa/disable',{method:'POST'});const d=await r.json();if(!r.ok){setMessage(d.error);return}setMessage('Two-factor authentication has been disabled.');setUser((u:any)=>({...u,twoFactorEnabled:false}));};
 return <div className="content"><div className="eyebrow">Security</div><h1 className="h1">Authentication & trust center</h1><p className="muted">Protect the account before enabling autonomous career actions.</p><div className="grid grid2" style={{marginTop:16}}><div className="card"><h2>Authentication scan</h2><p className="small muted">Review the account authentication posture and add an authenticator app as a second factor.</p><div className="stack" style={{marginTop:12}}><div className="notice"><strong>Email/password</strong><div className="small muted">Password is stored as a bcrypt hash; the platform never stores the raw password.</div></div><div className="notice"><strong>Authenticator app</strong><div className="small muted">{user?.twoFactorEnabled?'Enabled — a six-digit code is required at sign-in.':'Not enabled — recommended before AutoApply is activated.'}</div></div>{!user?.twoFactorEnabled&&!qr&&<button className="btn primary" onClick={setup} disabled={loading}>{loading?'Creating secure setup…':'Set up authenticator'}</button>}{qr&&<div className="stack"><img src={qr} alt="Authenticator setup QR code" style={{width:280,height:280,background:'#fff',padding:8,borderRadius:12}}/><div className="small muted">Scan with Google Authenticator, Microsoft Authenticator, 1Password, or another TOTP app.</div><div className="notice"><strong>Manual setup key</strong><div className="small" style={{wordBreak:'break-all'}}>{secret}</div></div><input className="input" inputMode="numeric" maxLength={6} placeholder="Enter 6-digit code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/><button className="btn primary" onClick={verify}>Verify and enable</button></div>}{user?.twoFactorEnabled&&<button className="btn danger" onClick={disable}>Disable authenticator</button>}{message&&<div className="pill" role="status" aria-live="polite">{message}</div>}</div></div><div className="card"><h2>Security controls</h2><ul className="list"><li>✓ Secure, httpOnly session cookie</li><li>✓ Server-side credential handling</li><li>✓ Encrypted TOTP secret at rest</li><li>✓ Rate-limit boundary available for production deployment</li><li>✓ Authentication events recorded in audit log</li><li>✓ Global AutoApply pause / kill switch</li></ul></div></div></div>
}
